// This file is generated by the rs-update-tests script

#include "rs-unit-test.hpp"

int main(int argc, char** argv) {

    RS::UnitTest::begin_tests(argc, argv);

    // version-test.cpp
    UNIT_TEST(rs_sci_version)

    // algorithms-test.cpp
    UNIT_TEST(rs_sci_algorithms_binomial_coefficients)
    UNIT_TEST(rs_sci_algorithms_interpolation)
    UNIT_TEST(rs_sci_algorithms_interpolated_map)
    UNIT_TEST(rs_sci_algorithms_interpolated_map_lin_log)
    UNIT_TEST(rs_sci_algorithms_interpolated_map_log_log)
    UNIT_TEST(rs_sci_algorithms_cubic_spline_map)
    UNIT_TEST(rs_sci_algorithms_precision_sum)
    UNIT_TEST(rs_sci_algorithms_line_integral)
    UNIT_TEST(rs_sci_algorithms_volume_integral)
    UNIT_TEST(rs_sci_algorithms_find_optimum)

    // constants-test.cpp
    UNIT_TEST(rs_sci_constants)

    // statistics-test.cpp
    UNIT_TEST(rs_sci_statistics_univariate)
    UNIT_TEST(rs_sci_statistics_bivariate)
    UNIT_TEST(rs_sci_statistics_combination)

    // unit-test.cpp

    return RS::UnitTest::end_tests();

}
